# main.py

from .init import init
from ..tools.read_files import read_files
from .setup import setup
from .public_parameter import PP

from .index_gen import index_gen
from .auth_gen import auth_gen
from .trapdoor_gen import trapdoor_gen
from .chall_gen import chall_gen
from .proof_gen import proof_gen
from .proof_verify import proof_verify


def main():
    # =====================
    # 1. init
    # =====================
    init()
    print("===== 系统公开参数 pp =====")
    print(f"PP['group']: \n{PP['group']}\n")
    print(f"PP['pair']: \n{PP['pair']}\n")
    print(f"G1 生成元 u:\n{PP['u']}\n")
    print(f"G1 生成元 g:\n{PP['g']}\n")
    print(f"私钥 x (Z_q^*): {PP['sk']}\n")
    print(f"公钥 y = g^x:\n{PP['pk']}\n")
    print(f"k0: {PP['k0']}\n")
    print(f"k1: {PP['k1']}\n")
    print(f"k2: {PP['k2']}\n")
    # =====================
    # 2. read_file
    # =====================
    keyword_input = {
        "f1.txt": ["first", "file"],
        "f2.txt": ["second", "file"],
        "f3.txt": ["third", "world"]
    }

    block_size = 1024

    files = read_files(
        # folder_path = "/home/jgj/MyRepository/storage-integrity-audit/testfiles",
        folder_path_test = "../../../testfiles",
        keyword_input=keyword_input,
        block_size=block_size
    )

    # =====================
    # 3. setup
    # =====================
    setup_result = setup(
        files=files,
        k0=PP["k0"],
        Enc=PP["Enc"],
        block_size=block_size
    )

    print("n =", setup_result.n)
    print("s =", setup_result.s)
    print("W =", setup_result.W)
    print("V =", setup_result.V)
    print("ID Table =", setup_result.id_table)
    print("File Table =", setup_result.file_table)
    print("C =", setup_result.C)

    # =====================
    # 4. index_gen
    # =====================
    I = index_gen(setup_result)
    print("Secure Index I =", I)

    # =====================
    # 5. auth_gen
    # =====================
    Phi = auth_gen(setup_result)
    print("Authenticator Set Φ =", Phi)

    # =====================
    # 6. trapdoor_gen
    # =====================
    keyword = "file"
    Tw = trapdoor_gen(keyword)
    print(f"Trapdoor Tw for keyword '{keyword}':", Tw)

    # =====================
    # 7. chall_gen
    # =====================
    c = 1
    Chal = chall_gen(
        trapdoor=Tw,
        s=setup_result.s,
        c=c
    )
    print(f"Challenge Chal for keyword '{keyword}':", Chal)
    # =====================
    # 8. proof_gen
    # =====================
    Proof_obj = proof_gen(
        challenge=Chal,
        secure_index=I,
        setup_result=setup_result,
        auth_set=Phi
    )
    print("Proof generated by cloud:", Proof_obj)
    # =====================
    # 9. proof_verify
    # =====================
    result = proof_verify(
        challenge=Chal,
        proof=Proof_obj
    )
    print("审计结果：", result)


if __name__ == "__main__":
    main()